### ISSUE TITLE
这个内核以及5.4版本的内核使用mips64el-linux-musl-cross交叉编译器编译在我们测试机启动卡死

### ISSUE THREAD

**Issue by suijingfeng** [loongson-community/linux-stable#20]
卡死的位置总是在打印
serial8250.0: ttyS0 at MMIO 0x1fe001e0 (irq = 58, base_baud = 1562500) is a 16550A
之后就花屏了，感觉串口驱动那里过不去跑飞了。
[boot.log](https://github.com/loongson-community/linux-stable/files/4181474/boot.log)

**Comment by suijingfeng** [comment]
![Screenshot_log](https://user-images.githubusercontent.com/10341056/74161561-16b5c400-4c5a-11ea-927e-7911d6398134.png)

下图就是我们的测试机主板
![IMG_20200210_233542](https://user-images.githubusercontent.com/10341056/74164466-c2f9a980-4c5e-11ea-8abd-2a0d4392c344.jpg)

之后都是乱码，但是在龙梦的主板上就是可以使用的，很奇怪

**Comment by suijingfeng** [comment]
又用我们的编译器将memcpy和memset优化去掉编译过去发现，和编译器好像没有关系，但都是交叉编译

**Comment by suijingfeng** [comment]
有一部分原因是xorg.conf 没弄好，还有一部分可能是测试机太老了使用pmon固件的原因，
我们测试机固件配置有问题，没有就是pci 类号和子类号，龙梦的主板是0300， 我们的0380，
xserver启动时， 通过libpciaccess库读取 /sys/class/ 。。。/下的 boot_vga, 导致出错。 
导致图形起不来。

**Comment by FlyGoat** [comment]
Hi, 抱歉刚刚才看到，串口乱码的原因三部分龙芯的设备串口时钟频率与规范不一致。解决方案是使用keep_bootcon cmdline让内核不要重新初始化串口继续使用early printk打印，或者修改
将 ’arch/mips/loongson64/common/serial.c‘
```
[MACH_LOONGSON_GENERIC]	= {PORT_M(2, 25000000), {} },
```
改为
```
[MACH_LOONGSON_GENERIC]	= {PORT_M(2, 25000000), {} },
```
。
谢谢。

**Comment by suijingfeng** [comment]
使用keep_bootcon cmdline确实有效, 但是启动命令行不能在加上 console=ttyS0，115200

**Comment by suijingfeng** [comment]
@FlyGoat
这个最早我无权现看公司的内核，这个串口问题被我司4.19.73的yijun和zenglu解决了
```
author	Zeng Lu <zenglu@loongson.cn>	
	Tue, 19 Nov 2019 17:57:30 +0800 (04:57 -0500)
committer	Jun Yi <yijun@loongson.cn>	
	Wed, 20 Nov 2019 10:11:35 +0800 (10:11 +0800)

MIPS: Loongson-3: change default cpu uart clk to 33MHz

Some old 3A3000 BIOS does not pass uart device infomation, 
so change the default uartclk to 33MHz which can be directly used in 3A3000.
```

我看到了之后我，我也这样在5.4.17和4.19上这样改了，
但是由于当时我使用的固件是pmon的， 可是启动不起来，所以我就十分迷惑。
后来换测试机，测试固件刷成UEFI后，内核能启动也就忽略了这个问题。
今天周日有时间重新改动测试了一下，串口打印确实正常了。

但是昆仑固件第一次启动时第一个会在读connector那里卡住，重启又正常了。
在UEFI固件又启动试了一次，串口打印是正常的。
嗨，造化弄人呀。。。

将 ’arch/mips/loongson64/common/serial.c‘

`[MACH_LOONGSON_GENERIC]	= {PORT_M(2, 25000000), {} },`

改为

`[MACH_LOONGSON_GENERIC]	= {PORT_M(2, 33000000), {} },`

十分感谢。
