### ISSUE TITLE
lemote-lynloong-2f-9003 which kernel should choice？

### ISSUE THREAD

**Issue by vastchen** [loongson-community/linux-stable#3]
i got a old loongon 2f computer .lemote-lynloong-2f-9003 i try many kernnel like mainline 
龙芯社区kernel  lemote2.6.3.x build kernel choice arch/mips/configs/lemote2f_defconfig buil the kernel ,cross build the kernel pmon load vmlinux success ，but when input 

g console=tty sdax=root 
alway get the screen 
zero            at           vo        v1 ... ...
00000000 0000000 00000000 ... 
i have no idear please help 
i found debain squeeze anheng 刘工 build the debain linux-image-2.6.27.59-lynloogn-2f-9003 but there is delete so i can't get the sources,somebody can't tell me how to do?

之前我得到了一台灵珑一体机9S2A 但是编译内核时没有一个编译成功的如上面说的选择主线kernel 龙芯社区的，以及龙梦的用arch/mips/configs/lemote2f_defconfig默认设置编译，都能编译成功，并且都能引导vmlinux，但是到了pmon选取系统分区启动时就一直显示双面的内容，请问如何解决，实在搜索了很多只有讲debain安装的那些文章。望知道的告知下，谢谢。

**Comment by FlyGoat** [comment]
你好，这个repo是Loongson-3A的内核repo。。尽管2F不是不能用，但是不包含9003一体机所使用的SM502桥片方案的驱动。我也不是没试过移植，不过缺乏调试手段也是比较头疼的事情。

9003唯一可以使用的一个内核是Lemote当时出厂的的2.6.27内核，我放在这里，你可以试试。
https://github.com/linux-loongson/linux-lemote-2.6/tree/lemote-9003-2.6.27.y
谢谢。

**Comment by FlyGoat** [comment]
I'm going to close this issue because the discussion had moved to http://ask.loongnix.org .
